Update notes.php
Jason2605/AdminPanel pull request #19
Opened 2016-12-19 14:18 UTC by itsJarrett

Update notes.php to enable the search of players by their playerid or uid.

2016-12-19 14:31 UTC, Jason2605 commented
Don't search by playerid, as that has changed in v5.0 of AL

2016-12-19 14:37 UTC, Jason2605 commented on notes.php
> +    $sqlget = "SELECT * FROM players WHERE CONCAT (`name`,`playerid`,`uid`) LIKE '%".$valuetosearch."%'";
Down search by playerid, or atleast have checks for pid too. See the players page.

2016-12-19 14:44 UTC, itsJarrett commented
Added support per 91da8c0.

2016-12-19 15:10 UTC, itsJarrett commented
Looked clean on my screen, I suppose it parsed differently when I commuted it.

2016-12-19 15:24 UTC, Jason2605 commented
Have you tested this works after the changes.

2016-12-19 23:59 UTC, Jason2605 commented on notes.php
> +                    <th>ID</th>
You love that tab key

2016-12-20 00:01 UTC, itsJarrett commented on notes.php
> +                    <th>ID</th>
https://gyazo.com/a4c108a830574a787a26cbc47e89b904 

Must be PHPStorm,  didn't press tab at all >_>

2016-12-20 00:07 UTC, Jason2605 commented on notes.php
> +                    <th>ID</th>
Just make sure you use 4 spaces for where a tab would be.

2016-12-20 00:16 UTC, Jason2605 requested changes
Tabs.

2016-12-20 00:29 UTC, itsJarrett commented
Reconfigured my IDE to change from tabs to spaces.

2016-12-20 00:31 UTC, Jason2605 commented
Much better.

2016-12-20 00:32 UTC, Jason2605 approved these changes

2016-12-20 00:32 UTC, merged